layout_spectrum: 1
name: Red Hill
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      format: rss
      path: /rss.xml
      number: 10
typography_spectrum: 1
color:
  brandStrength: 0.6195368
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5531915
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
