layout_spectrum: 0.1845878
typography_spectrum: 1
color:
  saturation: 0.2240143
  brandStrength: 0.6195368
  lightness: 0.6164874
  rhythmicContrast: 0.2329749
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Red Hill
