collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 1
  brandStrength: 0.5130597
  lightness: 1
  brandColors:
    - '#FFFFFF'
    - '#FF74BC'
    - '#333541'
    - '#BD3668'
    - '#4AB1E3'
  rhythmicContrast: 1
typography_spectrum: 0.5150376
layout_spectrum: 0.275653
name: Red Hill
