layout_spectrum: 0.5319149
name: Red Hill
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
  brandColors:
    - '#EBEFF2'
    - '#1E1E20'
    - '#403F3A'
    - '#9C9B99'
    - '#BDC9BD'
typography_spectrum: 0.3638298
